#!/bin/sh

set -eu

if ! getent group | grep -q "^pusher:" ; then
  echo "Group 'pusher' does not exist, creating"
  groupadd pusher
fi

if grep -q 'VAPID_PUBLIC_KEY=invalid_key' /etc/pusher/push-server.conf; then
  echo "push-server.conf contains default values, regenerating keys"
  for key in DATABASE_ENCRYPTION_KEY VAPID_PUBLIC_KEY VAPID_PRIVATE_KEY; do
    sed -i "/${key}/d" /etc/pusher/push-server.conf
    sed -i "/${key}/d" /etc/pusher/push-send.conf
  done
	push-keygen >> /etc/pusher/push-send.conf
  grep DATABASE_ENCRYPTION_KEY /etc/pusher/push-send.conf >> /etc/pusher/push-server.conf
  grep VAPID_PUBLIC_KEY /etc/pusher/push-send.conf >> /etc/pusher/push-server.conf
fi


# run migrations
DB_PATH=$(awk -F= '/^DATABASE_PATH=/ {print $2}' /etc/pusher/push-server.conf)
cd /usr/share/pusher \
  && sg pusher -c "/usr/share/pusher/migrations/migrate.sh ${DB_PATH}"

chgrp -R pusher /etc/pusher
